### ISSUE TITLE
Broken URL in Intro to GitHub Assignment

### ISSUE THREAD

**Issue by kyletower** [microsoft/Web-Dev-For-Beginners#1023] opened 2022-12-27 16:10 UTC
**Describe the bug**
There is a broken URL in the Intro to GitHub assignment

**To Reproduce**
1. Go to https://github.com/microsoft/Web-Dev-For-Beginners/tree/main/1-getting-started-lessons/2-github-basics
2. Click on Assignment: Complete [the First Week on GitHub training lab](https://lab.github.com/githubtraining/first-week-on-github)
3. See error

**Expected behavior**
This link should land on a page with the assignment.

**Comment by 31Sanskrati** [comment] 2022-12-27 16:43
Along with the above error, in **Review & Self Study** section [lab.github.com](https://lab.github.com/) link is not working.

**Comment by 31Sanskrati** [comment] 2022-12-27 16:46
I don't think the error occurs due to a broken link as the official website of github lab is showing the exact same error.

**Comment by bellodavid** [comment] 2022-12-30 12:00
Is this issue still open?

**Comment by saragibby** [comment] 2023-01-09 21:38
Duplicate of #1018

**Comment by saragibby** [comment] 2023-01-09 21:45
Resolved in #1042

**Closed by saragibby** 2023-01-09 21:45 UTC
Labels: bug, good first issue
